// Clickable muscle groups. Ids match the node names in assets/body.glb
// (m|<id>|L / m|<id>|R) and the keys of GROUPS in tools/build_model.py.
// view: which side the camera swings to when the group is selected.

export const MUSCLES = [
  { id: 'chest-upper',  name: 'Upper Chest',   region: 'Chest',     view: 'front', anat: 'Clavicular head of pectoralis major',
    job: 'Drives the arm forward and up across the body. The target of incline pressing.' },
  { id: 'chest',        name: 'Chest',         region: 'Chest',     view: 'front', anat: 'Sternocostal and abdominal heads of pectoralis major',
    job: 'The bulk of the pec. Pushes the arm forward and brings it across and down toward the hips.' },
  { id: 'delts-front',  name: 'Front Delts',   region: 'Shoulders', view: 'front', anat: 'Clavicular (anterior) deltoid',
    job: 'Raises the arm forward and overhead. Works hard in every press.' },
  { id: 'delts-side',   name: 'Side Delts',    region: 'Shoulders', view: 'side',  anat: 'Acromial (lateral) deltoid',
    job: 'Lifts the arm out to the side. The main driver of shoulder width.' },
  { id: 'delts-rear',   name: 'Rear Delts',    region: 'Shoulders', view: 'back',  anat: 'Spinal (posterior) deltoid',
    job: 'Pulls the arm back and rotates it outward. Balances all the pressing for healthy shoulders.' },
  { id: 'rotator-cuff', name: 'Rotator Cuff',  region: 'Shoulders', view: 'back',  anat: 'Infraspinatus, teres minor, supraspinatus',
    job: 'Keeps the ball of the shoulder centred in its socket and turns the arm outward.' },
  { id: 'traps',        name: 'Upper Traps',   region: 'Back',      view: 'back',  anat: 'Descending trapezius, levator scapulae',
    job: 'Shrugs and supports the shoulder girdle; holds heavy loads at your sides.' },
  { id: 'upper-back',   name: 'Mid Back',      region: 'Back',      view: 'back',  anat: 'Middle and lower trapezius, rhomboids, teres major',
    job: 'Squeezes the shoulder blades together and down. Thickness and posture.' },
  { id: 'lats',         name: 'Lats',          region: 'Back',      view: 'back',  anat: 'Latissimus dorsi',
    job: 'Pulls the arm down and back toward the hip. Builds back width.' },
  { id: 'lower-back',   name: 'Lower Back',    region: 'Back',      view: 'back',  anat: 'Erector spinae (iliocostalis, longissimus, spinalis)',
    job: 'Holds the spine straight under load and extends it.' },
  { id: 'biceps',       name: 'Biceps',        region: 'Arms',      view: 'front', anat: 'Biceps brachii, brachialis, coracobrachialis',
    job: 'Bends the elbow and turns the palm up. Brachialis underneath adds arm thickness.' },
  { id: 'triceps',      name: 'Triceps',       region: 'Arms',      view: 'back',  anat: 'Long, lateral and medial heads of triceps brachii, anconeus',
    job: 'Straightens the elbow. About two thirds of upper-arm size.' },
  { id: 'forearms',     name: 'Forearms',      region: 'Arms',      view: 'front', anat: 'Brachioradialis, wrist and finger flexors and extensors',
    job: 'Grip, wrist curling and extension, and elbow flexion with a neutral grip.' },
  { id: 'abs',          name: 'Abs',           region: 'Core',      view: 'front', anat: 'Rectus abdominis',
    job: 'Curls the ribcage toward the pelvis and braces the trunk against load.' },
  { id: 'obliques',     name: 'Obliques',      region: 'Core',      view: 'front', anat: 'External oblique',
    job: 'Rotates and side-bends the trunk, and resists rotation when you carry or press.' },
  { id: 'serratus',     name: 'Serratus',      region: 'Core',      view: 'side',  anat: 'Serratus anterior',
    job: 'Wraps the ribs and pulls the shoulder blade forward and up. Needed for healthy overhead work.' },
  { id: 'glutes',       name: 'Glutes',        region: 'Hips',      view: 'back',  anat: 'Gluteus maximus',
    job: 'Extends the hip. The strongest muscle for squatting, hinging and sprinting.' },
  { id: 'abductors',    name: 'Hip Abductors', region: 'Hips',      view: 'side',  anat: 'Gluteus medius, tensor fasciae latae',
    job: 'Moves the leg out to the side and keeps the pelvis level on one leg.' },
  { id: 'hip-flexors',  name: 'Hip Flexors',   region: 'Hips',      view: 'front', anat: 'Psoas major, iliacus, sartorius',
    job: 'Lifts the thigh toward the chest.' },
  { id: 'adductors',    name: 'Adductors',     region: 'Legs',      view: 'front', anat: 'Adductor magnus, longus, brevis, gracilis, pectineus',
    job: 'Pulls the legs together. Adductor magnus is a big hip extender out of a deep squat.' },
  { id: 'quads',        name: 'Quads',         region: 'Legs',      view: 'front', anat: 'Rectus femoris, vastus lateralis, vastus medialis',
    job: 'Straightens the knee. The main mover in squats and leg presses.' },
  { id: 'hamstrings',   name: 'Hamstrings',    region: 'Legs',      view: 'back',  anat: 'Biceps femoris, semitendinosus, semimembranosus',
    job: 'Bends the knee and extends the hip.' },
  { id: 'calves',       name: 'Calves',        region: 'Legs',      view: 'back',  anat: 'Gastrocnemius, soleus',
    job: 'Points the foot. Gastrocnemius works best with the knee straight, soleus with it bent.' },
  { id: 'shins',        name: 'Shins',         region: 'Legs',      view: 'front', anat: 'Tibialis anterior, peroneals, toe extensors',
    job: 'Lifts the foot and steadies the ankle. Helps knee and shin health.' },
  { id: 'neck',         name: 'Neck',          region: 'Head',      view: 'front', anat: 'Sternocleidomastoid, splenius, scalenes',
    job: 'Flexes, extends and turns the head.' },
];

export const MUSCLE = Object.fromEntries(MUSCLES.map(m => [m.id, m]));
